// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wpbtxicplutuxpldkutb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndwYnR4aWNwbHV0dXhwbGRrdXRiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNjQ0NDAsImV4cCI6MjA2Mzk0MDQ0MH0.qJvKk4jt3PwLfk3StepzYGG-lB0Ytf_OuEBXL6uBfZQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);